version: "3.7"
 
services:
 
  flask:
    build: ./flask
    container_name: raku
    restart: always
    ports:
     - :5002:5002
    depends_on:
     - db
                                    
   db:
    image: postgres
    container_name: postgres
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
    environment:
     POSTGRES_DB: db_name
     POSTGRES_USER: postgres_n
     POSTGRES_PASSWORD: postgres_p
    ports:
     - 5432:5432
