version: "3.7"
 
services:
  flask:
    build: ./flask
    container_name: raku
    volumes:
      - ./flask:/app
    ports:
     - 5002:5002
    depends_on:
     - db
    # command: bash -c "cd /app && flask db init && flask db migrate && flask db upgrade"
  db:
    image: postgres
    container_name: rakuSQL
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
    environment:
     POSTGRES_DB: db_name
     POSTGRES_USER: root
     POSTGRES_PASSWORD: root
    ports:
     - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 2210368@ecc.ac.jp
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5003:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
volumes:
  db-data:
  pgadmin-data: